import type { Metadata } from 'next';
import ClientLayout from './studentLayout';
import { UserProvider } from './contexts/userContext';
import { ChatProvider } from './contexts/chatContext';
import { NotificationProvider } from './contexts/notificationContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <NotificationProvider>
        <ChatProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </ChatProvider>
      </NotificationProvider>
    </UserProvider>
  )
}
