import type { Metadata } from 'next';
import ClientLayout from './studentLayout';
import { UserProvider } from './contexts/userContext';
import { ChatProvider } from './contexts/chatContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <ChatProvider>
        <ClientLayout>
          {children}
        </ClientLayout>
      </ChatProvider>
    </UserProvider>
  )
}
