import type { Metadata } from 'next';
import ClientLayout from './studentLayout';
import { UserProvider } from './contexts/userContext';
import { ChatProvider } from './contexts/chatContext';
import { NotificationProvider } from './contexts/notificationContext';
import { ClassProvider } from '@/app/contexts/studentClassContext';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export const metadata: Metadata = {
  title: 'EduConnect',
  description: 'Generated by create next app',
    icons: {
    icon: '/favicon.ico',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <NotificationProvider>
        <ClassProvider>
          <ChatProvider>
            <ClientLayout>
              {children}
              <ToastContainer position="bottom-right" autoClose={3000} />
            </ClientLayout>
          </ChatProvider>
        </ClassProvider>
      </NotificationProvider>
    </UserProvider>
  )
}
